sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt -qq update
  - sudo apt install  --no-install-recommends -y mono-devel ca-certificates-mono rpm wine1.8 bsdtar snapcraft gcc-multilib g++-multilib
  - npm install --global yarn

language: node_js
node_js:
  - "7"

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn add electron-builder
  - electron-builder -mw